version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:4000/api

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data/mongo:/data/db
