version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
